### ISSUE TITLE
Multiple occurrences of Kanji in kanji.db 

### ISSUE THREAD

**Issue by Rpronk91** [maarten990/KanjiTrainer#2]
SQLite Database Browser shows multiple occurrences (10355 times) of the Kanji 亜 (grade 8)
![kanjidb](https://cloud.githubusercontent.com/assets/1382190/7971231/85a821d6-0a43-11e5-8460-3f4ca92ddc9a.png)

**Comment by RijstwafelMetSmaak** [comment]
Can we just remove all duplicates from the database?

2015-06-03 22:57 GMT+02:00 Richard Pronk notifications@github.com:

**Comment by maarten990** [comment]
eb9d2db6cdae15ea3bc2b8b0fc122a1a16c9b741
