### ISSUE TITLE
Button events accessible while loading

### ISSUE THREAD

**Issue by RijstwafelMetSmaak** [maarten990/KanjiTrainer#8]
Buttons can be pressed using the hotkeys (1,2,...) while the page is being loaded.

Tried the button.disabled property, but this seemed to change nothing at all. nothing at all. nothing at all.

**Comment by maarten990** [comment]
![](http://vignette1.wikia.nocookie.net/simpsonstappedout/images/5/58/Tapped_Out_Stupid_Sexy_Flanders.png/revision/latest?cb=20141204210243)

**Comment by maarten990** [comment]
I think this is fixed by 09c82d45a69d06b93e6ea947cb1ed613a2f41c83 and 63a6f81aac93f1521aad010f5301b1c76f67f6dd
